name: Extract and Log Check Times

on:
  schedule:
    - cron: '*/29 * * * *' # Every 29 minutes
  push:
    branches:
      - main

jobs:
  extract-check-times:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch data from source
      run: |
        echo "Fetching data from source"
        curl -L -o data.txt "https://drive.google.com/uc?export=download&id=1-6p05WRNFuCef8OnlkexeZP-HR-hRXYl"
        echo "Fetch response code: $?"
        cat data.txt

    - name: Extract and log check times
      run: |
        echo "Extracting and logging check times"
        
        # Extract entire second line
        second_line=$(sed -n '2p' data.txt)
        
        # Log the entire second line
        echo "Entire Second Line: \"$second_line\""

        # Extract time from the second line
        computer_time=$(echo "$second_line" | cut -d',' -f2)
        
        # Ensure time is correctly extracted
        echo "Extracted Computer Check Time: \"$computer_time\""
        
        # Extract entire third line
        third_line=$(sed -n '3p' data.txt)
        
        # Log the entire third line
        echo "Entire Third Line: \"$third_line\""
        
        # Extract time from the third line
        ib_time=$(echo "$third_line" | cut -d',' -f2)
        
        # Ensure time is correctly extracted
        echo "Extracted IB Check Time: \"$ib_time\""

    - name: Calculate and log time differences
      run: |
        echo "Calculating and logging time differences"

        # Get current time in the same format
        current_time=$(date -u +"%m/%d/%Y %H:%M:%S")
        
        # Log current time
        echo "Current Time: \"$current_time\""
        
        # Convert times to seconds since epoch
        computer_epoch=$(date -d "$computer_time" +%s)
        ib_epoch=$(date -d "$ib_time" +%s)
        current_epoch=$(date -d "$current_time" +%s)
        
        # Calculate time differences
        diff_computer=$((current_epoch - computer_epoch))
        diff_ib=$((current_epoch - ib_epoch))
        
        # Convert differences to hours, minutes, seconds
        format_time_diff() {
            local total_seconds=$1
            local hours=$((total_seconds / 3600))
            local minutes=$(( (total_seconds % 3600) / 60))
            local seconds=$((total_seconds % 60))
            printf "%02d:%02d:%02d\n" $hours $minutes $seconds
        }
        
        time_diff_computer=$(format_time_diff $diff_computer)
        time_diff_ib=$(format_time_diff $diff_ib)
        
        # Log the results
        echo "Time Difference - Current Time vs Computer Check Time: \"$time_diff_computer\""
        echo "Time Difference - Current Time vs IB Check Time: \"$time_diff_ib\""
