name: Send Email via Gmail SMTP

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Send email via Gmail SMTP
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.GMAIL_USER }}
        SMTP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: recipient@example.com
      run: |
        echo "Sending email..."
        node -e "
          const nodemailer = require('nodemailer');
          const transporter = nodemailer.createTransport({
            host: process.env.SMTP_SERVER,
            port: process.env.SMTP_PORT,
            secure: false,
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASSWORD
            }
          });
          const message = {
            from: 'Your Name <${{ secrets.GMAIL_USER }}>',
            to: process.env.EMAIL_TO,
            subject: 'Hello from GitHub Actions',
            text: 'This is a test email sent from GitHub Actions using Gmail SMTP.'
          };
          transporter.sendMail(message, (error, info) => {
            if (error) {
              console.log('Error: ', error);
            } else {
              console.log('Email sent: ', info.response);
            }
          });
        "
