name: Send Email

on:
  schedule:
    - cron: '*/29 * * * *' # Every 29 minutes
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch data from source
      run: |
        echo "Fetching data from source"
        curl -L -o data.txt "https://drive.google.com/uc?export=download&id=1-6p05WRNFuCef8OnlkexeZP-HR-hRXYl"
        cat data.txt

    - name: Process times and calculate differences
      run: |
        echo "Processing times and calculating differences"
        
        second_line=$(sed -n '2p' data.txt)
        computer_time=$(echo "$second_line" | cut -d',' -f2)
        third_line=$(sed -n '3p' data.txt)
        ib_time=$(echo "$third_line" | cut -d',' -f2)
        
        current_time=$(TZ='Asia/Hong_Kong' date +"%m/%d/%Y %H:%M:%S")
        
        computer_epoch=$(date -d "$computer_time" +%s)
        ib_epoch=$(date -d "$ib_time" +%s)
        current_epoch=$(date -d "$current_time" +%s)
        
        diff_computer=$((current_epoch - computer_epoch))
        diff_ib=$((current_epoch - ib_epoch))
        
        format_time_diff() {
            local total_seconds=$1
            local hours=$((total_seconds / 3600))
            local minutes=$(( (total_seconds % 3600) / 60))
            local seconds=$((total_seconds % 60))
            printf "%02d:%02d:%02d\n" $hours $minutes $seconds
        }
        
        time_diff_computer=$(format_time_diff $diff_computer)
        time_diff_ib=$(format_time_diff $diff_ib)
        
        echo "Time Difference - Current Time vs Computer Check Time: \"$time_diff_computer\""
        echo "Time Difference - Current Time vs IB Check Time: \"$time_diff_ib\""

    - name: Send email via EmailJS
      run: |
        echo "Sending email via EmailJS"
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.EMAILJS_PRIVATE_KEY }}" \
          -d '{
              "service_id": "'"${{ secrets.EMAILJS_SERVICE_ID }}"'",
              "template_id": "'"${{ secrets.EMAILJS_TEMPLATE_ID }}"'",
              "user_id": "'"${{ secrets.EMAILJS_USER_ID }}"'",
              "template_params": {
                "name": "User",
                "notes": "Email sent from GitHub Actions!"
              }
            }' \
          https://api.emailjs.com/api/v1.0/email/send
        echo "Email sent"
