name: Send Email via Gmail

on:
  schedule:
    - cron: '*/3 * * * *' # Run the job every 3 minutes
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetch data from source
      run: |
        echo "Fetching data from source"
        curl -L -o data.txt "https://drive.google.com/uc?export=download&id=1-95wSJE41HJS65e6vsjR3KP51JK_Lvg9"
        cat data.txt

    - name: Process times and calculate differences
      id: process_times
      run: |
        echo "Processing times and calculating differences"
        
        second_line=$(sed -n '2p' data.txt)
        echo "DEBUG: second_line: $second_line"
        computer_time=$(echo "$second_line" | cut -d',' -f2)
        echo "DEBUG: computer_time: $computer_time"
        third_line=$(sed -n '3p' data.txt)
        echo "DEBUG: third_line: $third_line"
        ib_time=$(echo "$third_line" | cut -d',' -f2)
        echo "DEBUG: ib_time: $ib_time"
        
        current_time=$(TZ='Asia/Hong_Kong' date +"%m/%d/%Y %H:%M:%S")
        echo "DEBUG: current_time: $current_time"
        
        computer_epoch=$(date -d "$computer_time" +%s)
        echo "DEBUG: computer_epoch: $computer_epoch"
        ib_epoch=$(date -d "$ib_time" +%s)
        echo "DEBUG: ib_epoch: $ib_epoch"
        current_epoch=$(date -d "$current_time" +%s)
        echo "DEBUG: current_epoch: $current_epoch"
        
        diff_computer=$((current_epoch - computer_epoch))
        echo "DEBUG: diff_computer: $diff_computer"
        diff_ib=$((current_epoch - ib_epoch))
        echo "DEBUG: diff_ib: $diff_ib"
        
        format_time_diff() {
            local total_seconds=$1
            local hours=$((total_seconds / 3600))
            local minutes=$(( (total_seconds % 3600) / 60))
            local seconds=$((total_seconds % 60))
            printf "%02d:%02d:%02d\n" $hours $minutes $seconds
        }
        
        time_diff_computer=$(format_time_diff $diff_computer)
        time_diff_ib=$(format_time_diff $diff_ib)
        
        echo "Time Difference - Current Time vs Computer Check Time: \"$time_diff_computer\""
        echo "Time Difference - Current Time vs IB Check Time: \"$time_diff_ib\""
        echo "Overwriting and writing to output.txt"
        echo "Current Time (HKT): $current_time" > output.txt
        echo "Computer Check Time: $computer_time" >> output.txt
        echo "IB Check Time: $ib_time" >> output.txt
        echo "Time Difference - Current Time vs Computer Check Time: $time_diff_computer" >> output.txt
        echo "Time Difference - Current Time vs IB Check Time: $time_diff_ib" >> output.txt
        echo "time_diff_computer=$time_diff_computer" >> output.txt
        echo "time_diff_ib=$time_diff_ib" >> output.txt
        echo "DEBUG: Content of output.txt after writing:"
        cat output.txt

        current_hour=$(date +'%H')
        current_minute=$(date +'%M')
        current_day=$(date +'%u') # 1 (Monday) to 7 (Sunday)
        should_send_email=true
        if [ $current_day -ge 1 ] && [ $current_day -le 5 ]; then
          if [ $current_hour -eq 3 ] && [ $current_minute -lt 15 ]; then
            should_send_email=false
          elif [ $current_hour -ge 3 ] && [ $current_hour -lt 9 ]; then
            should_send_email=false
          elif [ $current_hour -eq 9 ] && [ $current_minute -lt 15 ]; then
            should_send_email=false
          fi
        elif [ $current_day -eq 6 ] && [ $current_hour -ge 3 ]; then
          should_send_email=false
        elif [ $current_day -eq 7 ]; then
          should_send_email=false
        fi
        if [ $diff_computer -gt 240 ] || [ $diff_ib -gt 240 ]; then
          if [ "$should_send_email" = true ]; then
            echo "SEND_EMAIL=true" >> $GITHUB_ENV
          else
            echo "SEND_EMAIL=false" >> $GITHUB_ENV
          fi
        else
          echo "SEND_EMAIL=false" >> $GITHUB_ENV
        fi
        echo "DEBUG: SEND_EMAIL: $SEND_EMAIL"
        echo "DEBUG: Time diff computer: $time_diff_computer"
        echo "DEBUG: Time diff IB: $time_diff_ib"
        echo "DEBUG: diff_computer: $diff_computer"
        echo "DEBUG: diff_ib: $diff_ib"
        echo "DEBUG: Environment SEND_EMAIL: ${{ env.SEND_EMAIL }}"
        echo "DEBUG: Final Content of output.txt:"
        cat output.txt
        if [ -f output.txt ]; then
          echo "output.txt exists"
        else
          echo "output.txt does not exist"
        fi

    - name: Upload output.txt as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-log
        path: output.txt

    - name: Send email via Gmail SMTP
      if: env.SEND_EMAIL == 'true'
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.GMAIL_USER }}
        SMTP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: thdennis.dc@gmail.com
        TIME_DIFF_COMPUTER: ${{ env.time_diff_computer }}
        TIME_DIFF_IB: ${{ env.time_diff_ib }}
      run: |
        echo "Sending email..."
        node -e "
          const nodemailer = require('nodemailer');
          const transporter = nodemailer.createTransport({
            host: process.env.SMTP_SERVER,
            port: process.env.SMTP_PORT,
            secure: false,
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASSWORD
            }
          });
          const message = {
            from: 'Your Name <${{ secrets.GMAIL_USER }}>',
