name: Send Email via Gmail

on:
  schedule:
    - cron: '*/3 * * * *' # Run the job every minute
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetch data from source
      run: |
        echo "Fetching data from source"
        curl -L -o data.txt "https://drive.google.com/uc?export=download&id=1-6p05WRNFuCef8OnlkexeZP-HR-hRXYl"
        cat data.txt

    - name: Process times and calculate differences
      id: process_times
      run: |
        echo "Processing times and calculating differences"
        
        second_line=$(sed -n '2p' data.txt)
        computer_time=$(echo "$second_line" | cut -d',' -f2)
        third_line=$(sed -n '3p' data.txt)
        ib_time=$(echo "$third_line" | cut -d',' -f2)
        
        current_time=$(TZ='Asia/Hong_Kong' date +"%m/%d/%Y %H:%M:%S")
        
        computer_epoch=$(date -d "$computer_time" +%s)
        ib_epoch=$(date -d "$ib_time" +%s)
        current_epoch=$(date -d "$current_time" +%s)
        
        diff_computer=$((current_epoch - computer_epoch))
        diff_ib=$((current_epoch - ib_epoch))
        
        format_time_diff() {
            local total_seconds=$1
            local hours=$((total_seconds / 3600))
            local minutes=$(( (total_seconds % 3600) / 60))
            local seconds=$((total_seconds % 60))
            printf "%02d:%02d:%02d\n" $hours $minutes $seconds
        }
        
        time_diff_computer=$(format_time_diff $diff_computer)
        time_diff_ib=$(format_time_diff $diff_ib)
        
        echo "Time Difference - Current Time vs Computer Check Time: \"$time_diff_computer\""
        echo "Time Difference - Current Time vs IB Check Time: \"$time_diff_ib\""

        echo "time_diff_computer=$time_diff_computer" > output.txt
        echo "time_diff_ib=$time_diff_ib" >> output.txt

        if [ $diff_computer -gt 1200 ] || [ $diff_ib -gt 1200 ]; then
            echo "SEND_EMAIL=true" >> $GITHUB_ENV
        else
            echo "SEND_EMAIL=false" >> $GITHUB_ENV
        fi

    - name: Send email via Gmail SMTP
      if: env.SEND_EMAIL == 'true'
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.GMAIL_USER }}
        SMTP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        EMAIL_TO: thdennis.dc@gmail.com
        TIME_DIFF_COMPUTER: ${{ env.time_diff_computer }}
        TIME_DIFF_IB: ${{ env.time_diff_ib }}
      run: |
        echo "Sending email..."
        node -e "
          const nodemailer = require('nodemailer');
          const transporter = nodemailer.createTransport({
            host: process.env.SMTP_SERVER,
            port: process.env.SMTP_PORT,
            secure: false,
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASSWORD
            }
          });
          const message = {
            from: 'Your Name <${{ secrets.GMAIL_USER }}>',
            to: process.env.EMAIL_TO,
            subject: 'Errorsp Alert from GitHub Actions',
            text: 'Time Difference - Current Time vs Computer Check Time: ' + process.env.TIME_DIFF_COMPUTER + '\nTime Difference - Current Time vs IB Check Time: ' + process.env.TIME_DIFF_IB
          };
          transporter.sendMail(message, (error, info) => {
            if (error) {
              console.log('Error: ', error);
            } else {
              console.log('Email sent: ', info.response);
            }
          });
        "
