name: Update data.txt

on:
  schedule:
    - cron: '*/2 * * * *' # Every 2 minutes
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Fetch data from source
      run: |
        curl -o data.txt "https://drive.google.com/file/d/1-6p05WRNFuCef8OnlkexeZP-HR-hRXYl/view?usp=sharing" # Replace with the URL to your source, like a Google Drive public link

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.txt
        git commit -m "Update data.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ 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 }}
